name: "Setup Algorand"
description: "Setup Algorand"
inputs:
  python-version: # python version
    description: "Python version"
    required: true
    default: "3.10"
runs:
  using: "composite"
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Checkout algorand sandbox
      uses: actions/checkout@master
      with:
        repository: algorand/sandbox

    - name: Print Directory
      run: |
        ls -ltr

    # - name: copy config
    #   run: cp config.test sandbox/

    # - name: Run Algorand Sandbox
    #   run: cd sandbox && ./sandbox up test -v
