name: "Setup Algorand"
description: "Setup Algorand"
inputs:
  python-version: # python version
    description: "Python version"
    required: true
    default: "3.10"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Checkout algorand sandbox
      uses: actions/checkout@v2
      with:
        repository: algorand/sandbox
        path: algorand-sandbox

    - name: Print Directory
      shell: bash
      run: |
        ls -ltr

    - name: copy config
      shell: bash
      run: cp config.test sandbox/

    # - name: Run Algorand Sandbox
    #   run: cd sandbox && ./sandbox up test -v
