name: "Setup Algorand"
description: "Setup Algorand"
inputs:
  python-version: # python version
    description: "Python version"
    required: true
    default: "3.10"
runs:
  using: "composite"
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Checkout algorand sandbox
      uses: actions/checkout@master
      with:
        repository: algorand/sandbox

    - name: Print Directory
      run: |
        ls -ltr

    - name: copy config
      run: cp config.test sandbox/

    - name: Run Algorand Sandbox
      working-directory: sandbox
      shell: 'script -q -e -c "bash {0}"' # hacky hack to make TTY work
      run: ./sandbox up test -v
