name: "Install PyTeal"
description: "Install PyTeal"
inputs:
  python-version: # python version
    description: "Python version"
    required: false
    default: "3.10"
  pyteal-version: # pyteal version
    description: "PyTeal Version"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install PyTeal Latest Version
      if: ${{ inputs.pyteal-version == '' }}
      shell: bash
      run: |
        pip3 install pyteal

    - name: Install PyTeal ${{ inputs.pyteal-version }}
      if: ${{ inputs.pyteal-version != '' }}
      shell: bash
      run: |
        pip3 install pyteal==${{ inputs.pyteal-version }}
